# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - label: "${TPU_VERSION:-tpu7x} Correctness tests for Multi-host P/D disaggregation"
    key: "${TPU_VERSION:-tpu7x}_multi_host_disagg_CorrectnessTest"
    soft_fail: true
    agents:
      # queue: tpu_v7x_16_queue
      # hostname: tpu7x-16-ci-2-cicd-us-central1-c
      queue: default
      hostname: tpu7x-8-ci-16-cicd-us-central1-c
    env:
      TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      TEST_MODE: 2 # only run correctness test
      DECODE_TPU_NAME: tpu7x-8-ci-17-cicd-us-central1-c
      DECODE_ZONE: us-central1-c
    commands:
      - |
        .buildkite/e2e/run_multi_disagg.sh

  - label: "${TPU_VERSION:-tpu7x} Record correctness test result for Multi-host P/D disaggregation"
    key: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu7x}_multi_host_disagg_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      CI_TARGET: "Multi-host P/D disaggregation"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi_host_disagg_CorrectnessTest

  # - label: "${TPU_VERSION:-tpu7x} Performance tests for Multi-host P/D disaggregation"
  #   key: "${TPU_VERSION:-tpu7x}_multi_host_disagg_PerformanceTest"
  #   depends_on: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_CorrectnessTest"
  #   soft_fail: true
  #   agents:
  #     queue: tpu_v7x_16_queue
  #   env:
  #     TPU_VERSION: "${TPU_VERSION:-tpu7x}"
  #     TEST_MODE: 1 # only run performance test
  #   commands:
  #     - |
  #       .buildkite/e2e/run_multi_disagg.sh

  # - label: "${TPU_VERSION:-tpu7x} Record performance test result for Multi-host P/D disaggregation"
  #   key: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_PerformanceTest"
  #   depends_on: "${TPU_VERSION:-tpu7x}_multi_host_disagg_PerformanceTest"
  #   env:
  #     CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
  #     CI_TARGET: "Multi-host P/D disaggregation"
  #     CI_STAGE: "PerformanceTest"
  #     CI_CATEGORY: "feature support matrix"
  #   agents:
  #     queue: cpu
  #   commands:
  #     - |
  #       .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi_host_disagg_PerformanceTest

  - label: "${TPU_VERSION:-tpu7x} Correctness tests for Multi-host P/D disaggregation with Prefill Offloading"
    key: "${TPU_VERSION:-tpu7x}_multi_host_disagg_offload_CorrectnessTest"
    soft_fail: true
    agents:
      queue: default
      hostname: tpu7x-8-ci-16-cicd-us-central1-c
    env:
      TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      TEST_MODE: 2 # only run correctness test
      DECODE_TPU_NAME: tpu7x-8-ci-17-cicd-us-central1-c
      DECODE_ZONE: us-central1-c
      TPU_ENABLE_D2H_TRANSFER: "true"
      TPU_MAX_HOST_KV_BUFFER_SIZE: "128"
    commands:
      - |
        .buildkite/e2e/run_multi_disagg_offload.sh

  - label: "${TPU_VERSION:-tpu7x} Record correctness test result for Multi-host P/D disaggregation with Prefill Offloading"
    key: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_offload_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu7x}_multi_host_disagg_offload_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      CI_TARGET: "Multi-host P/D disaggregation with Prefill Offloading"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi_host_disagg_offload_CorrectnessTest

  # - label: "${TPU_VERSION:-tpu7x} Performance tests for Multi-host P/D disaggregation with Prefill Offloading"
  #   key: "${TPU_VERSION:-tpu7x}_multi_host_disagg_offload_PerformanceTest"
  #   depends_on: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_offload_CorrectnessTest"
  #   soft_fail: true
  #   agents:
  #     queue: default
  #     hostname: tpu7x-8-ci-16-cicd-us-central1-c
  #   env:
  #     TPU_VERSION: "${TPU_VERSION:-tpu7x}"
  #     TEST_MODE: 1 # only run performance test
  #     DECODE_TPU_NAME: tpu7x-8-ci-17-cicd-us-central1-c
  #     DECODE_ZONE: us-central1-c
  #     TPU_ENABLE_D2H_TRANSFER: "true"
  #     TPU_MAX_HOST_KV_BUFFER_SIZE: "128"
  #   commands:
  #     - |
  #       .buildkite/e2e/run_multi_disagg_offload.sh

  # - label: "${TPU_VERSION:-tpu7x} Record performance test result for Multi-host P/D disaggregation with Prefill Offloading"
  #   key: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_offload_PerformanceTest"
  #   depends_on: "${TPU_VERSION:-tpu7x}_multi_host_disagg_offload_PerformanceTest"
  #   env:
  #     CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
  #     CI_TARGET: "Multi-host P/D disaggregation with Prefill Offloading"
  #     CI_STAGE: "PerformanceTest"
  #     CI_CATEGORY: "feature support matrix"
  #   agents:
  #     queue: cpu
  #   commands:
  #     - |
  #       .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi_host_disagg_offload_PerformanceTest

  - label: "${TPU_VERSION:-tpu7x} Correctness tests for Multi-host P/D disaggregation with Speculative Decoding"
    key: "${TPU_VERSION:-tpu7x}_multi_host_disagg_speculative_CorrectnessTest"
    soft_fail: true
    agents:
      queue: default
      hostname: tpu7x-8-ci-16-cicd-us-central1-c
    env:
      TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      MODEL: "Qwen/Qwen3-0.6B"
      LOAD_FORMAT: "auto"
      SPECULATIVE_CONFIG: '{"method":"ngram","prompt_lookup_max":5,"prompt_lookup_min":3,"num_speculative_tokens":3}'
      DRAFT_MODEL_IMPL_TYPE: "auto"
      DECODE_TPU_NAME: tpu7x-8-ci-17-cicd-us-central1-c
      DECODE_ZONE: us-central1-c
      TEST_MODE: 2 # only run correctness test
    commands:
      - |
        .buildkite/e2e/run_multi_disagg_speculative.sh

  - label: "${TPU_VERSION:-tpu7x} Record correctness test result for Multi-host P/D disaggregation with Speculative Decoding"
    key: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_speculative_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu7x}_multi_host_disagg_speculative_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      CI_TARGET: "Multi-host P/D disaggregation with Speculative Decoding"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi_host_disagg_speculative_CorrectnessTest

  # - label: "${TPU_VERSION:-tpu7x} Performance tests for Multi-host P/D disaggregation with Speculative Decoding"
  #   key: "${TPU_VERSION:-tpu7x}_multi_host_disagg_speculative_PerformanceTest"
  #   depends_on: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_speculative_CorrectnessTest"
  #   soft_fail: true
  #   agents:
  #     queue: default
  #     hostname: tpu7x-8-ci-16-cicd-us-central1-c
  #   env:
  #     TPU_VERSION: "${TPU_VERSION:-tpu7x}"
  #     MODEL: "Qwen/Qwen3-0.6B"
  #     LOAD_FORMAT: "auto"
  #     SPECULATIVE_CONFIG: '{"method":"ngram","prompt_lookup_max":5,"prompt_lookup_min":3,"num_speculative_tokens":3}'
  #     DRAFT_MODEL_IMPL_TYPE: "auto"
  #     DECODE_TPU_NAME: tpu7x-8-ci-17-cicd-us-central1-c
  #     DECODE_ZONE: us-central1-c
  #     TEST_MODE: 1 # only run performance test
  #   commands:
  #     - |
  #       .buildkite/e2e/run_multi_disagg_speculative.sh

  # - label: "${TPU_VERSION:-tpu7x} Record performance test result for Multi-host P/D disaggregation with Speculative Decoding"
  #   key: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_speculative_PerformanceTest"
  #   depends_on: "${TPU_VERSION:-tpu7x}_multi_host_disagg_speculative_PerformanceTest"
  #   env:
  #     CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
  #     CI_TARGET: "Multi-host P/D disaggregation with Speculative Decoding"
  #     CI_STAGE: "PerformanceTest"
  #     CI_CATEGORY: "feature support matrix"
  #   agents:
  #     queue: cpu
  #   commands:
  #     - |
  #       .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi_host_disagg_speculative_PerformanceTest
